#!/bin/bash

# Instalação do phpMyAdmin
sudo apt update
sudo apt install phpmyadmin -y

# Configuração do Apache
echo 'Include /etc/phpmyadmin/apache.conf' | sudo tee -a /etc/apache2/apache2.conf
sudo systemctl restart apache2

# Configuração do Nginx
echo 'location /phpmyadmin {' | sudo tee -a /etc/nginx/sites-available/default
echo '  root /usr/share/;' | sudo tee -a /etc/nginx/sites-available/default
echo '  index index.php index.html index.htm;' | sudo tee -a /etc/nginx/sites-available/default
echo '  location ~ ^/phpmyadmin/(.+\.php)$ {' | sudo tee -a /etc/nginx/sites-available/default
echo '    try_files $uri =404;' | sudo tee -a /etc/nginx/sites-available/default
echo '    fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;' | sudo tee -a /etc/nginx/sites-available/default
echo '    fastcgi_index index.php;' | sudo tee -a /etc/nginx/sites-available/default
echo '    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;' | sudo tee -a /etc/nginx/sites-available/default
echo '    include fastcgi_params;' | sudo tee -a /etc/nginx/sites-available/default
echo '  }' | sudo tee -a /etc/nginx/sites-available/default
echo '  location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {' | sudo tee -a /etc/nginx/sites-available/default
echo '    root /usr/share/;' | sudo tee -a /etc/nginx/sites-available/default
echo '  }' | sudo tee -a /etc/nginx/sites-available/default
echo '}' | sudo tee -a /etc/nginx/sites-available/default
sudo systemctl restart nginx

# Configuração do phpMyAdmin
sudo cp /etc/phpmyadmin/config.sample.inc.php /etc/phpmyadmin/config.inc.php
sudo sed -i 's/\$cfg\['\''blowfish_secret'\''\] = '\'''\'';/\$cfg\['\''blowfish_secret'\''\] = '\''yoursecretphrasehere'\'';/g' /etc/phpmyadmin/config.inc.php
sudo sed -i 's/\/\/ \$cfg\['\''Servers'\''\]\[\$i\]\['\''AllowNoPassword'\''\] = true;/\$cfg\['\''Servers'\''\]\[\$i\]\['\''AllowNoPassword'\''\] = true;/g' /etc/phpmyadmin/config.inc.php
sudo systemctl restart apache2
sudo systemctl restart nginx

echo 'O phpMyAdmin foi instalado e configurado com sucesso!'
